# Generated by Django 3.0.2 on 2020-02-02 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsVoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote_count', models.IntegerField(default=0)),
                ('downvote_count', models.IntegerField(default=0)),
                ('downvote', models.ManyToManyField(related_name='downvoted_news', to=settings.AUTH_USER_MODEL)),
                ('upvote', models.ManyToManyField(related_name='upvoted_news', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('news_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('news', models.TextField(unique=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('news_conn', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news_model', to='Dashboard.NewsVoteModel')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_posted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
