# Generated by Django 3.0.2 on 2020-01-31 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsvotemodel',
            name='news_conn',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news_model', to='Dashboard.NewsModel'),
        ),
    ]
