# Generated by Django 3.0.2 on 2020-02-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='fake',
            field=models.BooleanField(default=False),
        ),
    ]
