# Generated by Django 3.0.2 on 2020-02-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_newsmodel_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
    ]
