# Generated by Django 3.0.2 on 2020-02-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_newsmodel_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='news_img_link',
            field=models.TextField(blank=True),
        ),
    ]
