# Generated by Django 3.0.2 on 2020-02-08 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20200208_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodel',
            name='voted_news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='voted_news', to='Dashboard.NewsModel'),
        ),
    ]
