# Generated by Django 3.0.2 on 2020-02-08 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0004_auto_20200208_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
