# Generated by Django 3.0.2 on 2020-02-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_remove_userdatamodel_voted_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatamodel',
            name='accuracy_perc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userdatamodel',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
    ]
